# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x19\x61pi.unsafe.analyzer_delta\"\x06\n\x04Void\"\xf6\x01\n\x04\x44\x61ta\x12G\n\x0cnewton_depth\x18\x01 \x01(\x0b\x32/.api.unsafe.analyzer_delta.Data.NewtonDepthDataH\x00\x12R\n\x0ctachyon_data\x18\x02 \x01(\x0b\x32:.api.unsafe.analyzer_delta.Data.SubspaceTachyonScannerDataH\x00\x1a\x1e\n\x0fNewtonDepthData\x12\x0b\n\x03hex\x18\x01 \x01(\t\x1a)\n\x1aSubspaceTachyonScannerData\x12\x0b\n\x03hex\x18\x01 \x01(\tB\x06\n\x04\x64\x61ta2p\n\x15\x41nalyzerDeltaEndpoint\x12W\n\x11read_continuously\x12\x1f.api.unsafe.analyzer_delta.Void\x1a\x1f.api.unsafe.analyzer_delta.Data0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=40
  _VOID._serialized_end=46
  _DATA._serialized_start=49
  _DATA._serialized_end=295
  _DATA_NEWTONDEPTHDATA._serialized_start=214
  _DATA_NEWTONDEPTHDATA._serialized_end=244
  _DATA_SUBSPACETACHYONSCANNERDATA._serialized_start=246
  _DATA_SUBSPACETACHYONSCANNERDATA._serialized_end=287
  _ANALYZERDELTAENDPOINT._serialized_start=297
  _ANALYZERDELTAENDPOINT._serialized_end=409
# @@protoc_insertion_point(module_scope)
