# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x1d\x61pi.unsafe.sensor_void_energy\"\x06\n\x04Void\"\x1d\n\nSensorData\x12\x0f\n\x07hexdata\x18\x01 \x01(\t2|\n\x16SensorVoidEnergyServer\x12\x62\n\x10read_sensor_data\x12#.api.unsafe.sensor_void_energy.Void\x1a).api.unsafe.sensor_void_energy.SensorDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOID']._serialized_start=44
  _globals['_VOID']._serialized_end=50
  _globals['_SENSORDATA']._serialized_start=52
  _globals['_SENSORDATA']._serialized_end=81
  _globals['_SENSORVOIDENERGYSERVER']._serialized_start=83
  _globals['_SENSORVOIDENERGYSERVER']._serialized_end=207
# @@protoc_insertion_point(module_scope)
