# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x18\x61pi.unsafe.hackingdevice\")\n\x19SecretStationDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"\x06\n\x04Void2\x88\x01\n\x13HackingDeviceServer\x12q\n\x18read_secret_station_data\x12\x1e.api.unsafe.hackingdevice.Void\x1a\x33.api.unsafe.hackingdevice.SecretStationDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECRETSTATIONDATARESPONSE']._serialized_start=39
  _globals['_SECRETSTATIONDATARESPONSE']._serialized_end=80
  _globals['_VOID']._serialized_start=82
  _globals['_VOID']._serialized_end=88
  _globals['_HACKINGDEVICESERVER']._serialized_start=91
  _globals['_HACKINGDEVICESERVER']._serialized_end=227
# @@protoc_insertion_point(module_scope)
